title: My Portfolio
author: Brandi Chavez
email: brandi.nicole22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Brandi and I'm a Web Developer and mom of 2. I love
  front and backend development. Ask me anything or scroll on to 
  see some projects of mine.
# social links
instagram_username: thebartendingmama
github_username:  brandii347

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-hacker
